// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Pagination: typeof import('./components/Pagination.vue')['default']
    TableConfigure: typeof import('./components/TableConfigure.vue')['default']
    TableV2: typeof import('./components/TableV2.vue')['default']
  }
}

export {}
