// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    _Pagination: typeof import('./components/_Pagination.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
    TablePagination: typeof import('./components/TablePagination.vue')['default']
  }
}

export {}
