// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Table: typeof import('./components/Table.vue')['default']
    TableBody: typeof import('./components/TableBody.vue')['default']
    TableFilters: typeof import('./components/TableFilters.vue')['default']
    TableHead: typeof import('./components/TableHead.vue')['default']
    TablePagination: typeof import('./components/TablePagination.vue')['default']
    TableRow: typeof import('./components/TableRow.vue')['default']
    TableRowActionItems: typeof import('./components/TableRowActionItems.vue')['default']
    TableSearch: typeof import('./components/TableSearch.vue')['default']
  }
}

export {}
